server:
  port: 8081
spring:
  application:
    name: proposal-service
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3308/proposalSystem?createDatabaseIfNotExist=true}
    username: ${MYSQL_PASS}
    password: ${MYSQL_PASS}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
    listener:
      simple:
        auto-startup: true
    queue:
      credit:
        analysis: queue.credit.analysis
      notification:
        proposal-status: queue.proposal.status
      documentation:
        documentation-info: queue.documentation
    exchange:
      credit: credit.exchange
      proposal-notification: status.exchange
      documentation: document.exchange