server:
  port: 8081
spring:
  application:
    name: proposal-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/proposalSystem?createDatabaseIfNotExist=true
    username: ${MYSQL_PASS}
    password: ${MYSQL_PASS}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
    listener:
      simple:
        auto-startup: true
    queue:
      credit:
        analysis: queue.credit.analysis
    exchange:
      credit: credit.exchange