services:
  db:
    image: mysql
    container_name: proposalDB-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - proposalData:/var/lib/mysql

volumes:
  proposalData: