server:
  port: 8083
spring:
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      s3:
        bucket: proposal-documents-murillo
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
    listener:
      simple:
        auto-startup: true
    queue:
      notification:
        proposal-receipt: queue.notification.receipt
    exchange:
      notification: notification.receipt.exchange
