server:
  port: 8080
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/userSystem?createDatabaseIfNotExist=true
    username: ${MYSQL_PASS}
    password: ${MYSQL_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT}
            client-secret: ${GOOGLE_SECRET}
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
    listener:
      simple:
        auto-startup: true
    queue:
      notification-validation: queue.notification.user.validation
      notification-created: queue.notification.user.created
    exchange: notification.exchange


google:
  default:
    password: ${GOOGLE_DEFAULT_PASSWORD}
