server:
  port: 8082
spring:
  application:
    name: credit-analysis-application
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
    listener:
      simple:
        auto-startup: true
    queue:
      credit:
        analyzed-credit: queue.analyzed.credit
    exchange:
      analyzed-credit: analyzed.exchange
